### ISSUE TITLE
Error when run ccdl.py

### ISSUE THREAD

**Issue by int-0x03** [Drovosek01/adobe-packager#17]
I get some error 'no such file or directory'

```
python3 ./ccdl.py     
=================================
= Adobe macOS Package Generator =
============= 0.1.4 =============

Do you want to make M1 native packages (Y/n): 
Downloading products.xml

https://cdn-ffc.oobesaas.adobe.com/core/v4/products/all?_type=xml&channel=ccm,sti&platform=macuniversal,osx10-64,osx10&productType=Desktop
Source URL is: https://cdn-ffc.oobesaas.adobe.com/core/v4/products/all?_type=xml&channel=ccm,sti&platform=macuniversal,osx10-64,osx10&productType=Desktop
Source URL is: https://cdn-ffc.oobesaas.adobe.com/core/v4/products/all?_type=xml&channel=ccm,sti&platform=macarm64,macuniversal&productType=Desktop
Parsing products.xml
CDN: https://ccmdls.adobe.com
Note: If the Adobe program is not listed here, there is no native M1 version.
      Use the non native version with Rosetta 2 until an M1 version is avaliable.
23 products found:

[AEFTBETA] After Effects (Beta)
[AICY] InCopy
[AME] Media Encoder
[AMEBETA] Media Encoder (Beta)
[AUDT] Audition
[AUDTBETA] Audition (Beta)
[CHAR] Character Animator
[CHARBETA] Character Animator (Beta)
[DRWV] Dreamweaver
[IDSN] InDesign
[IDSNBETA] InDesign (Beta)
[ILST] Illustrator
[LRCC] Lightroom
[LTRM] Lightroom Classic
[PHSP] Photoshop
[PHSPBETA] Photoshop (Beta)
[PPRO] Premiere Pro
[PPROBETA] Premiere Pro (Beta)
[RUSH] Premiere Rush
[RUSHBETA] Premiere Rush (Beta)
[SPRK] XD
[SPRKBE] XD (Beta)
[UXPD] UXP Developer Tools

Please enter the SAP Code of the desired product (eg. PHSP for Photoshop): ILST

Illustrator Platform: macuniversal - 25.3.1
Illustrator Platform: macuniversal - 25.4.1
Illustrator Platform: macuniversal - 26.0
Illustrator Platform: macuniversal - 26.0.1

Please enter the desired version. Nothing for 26.0.1: 

Available languages: en_US, en_GB, en_IL, en_AE, es_ES, es_MX, pt_BR, fr_FR, fr_CA, fr_MA, it_IT, de_DE, nl_NL, ru_RU, uk_UA, zh_TW, zh_CN, ja_JP, ko_KR, pl_PL, hu_HU, cs_CZ, tr_TR, sv_SE, nb_NO, fi_FI, da_DK, ALL

Please enter the desired install language, or nothing for [ru_RU]: 

Please navigate to the desired downloads folder, or cancel to abort.

sapCode: ILST
version: 26.0.1
installLanguage: ru_RU
dest: /Users/int-0x03/Documents/Install ILST_26.0.1-ru_RU-macuniversal.app
[{'sapCode': 'ILST', 'version': '26.0.1', 'buildGuid': '03160a31-1d2f-4b73-bc82-cceaaab8cf7a'}, {'sapCode': 'COCM', 'version': '1.0', 'buildGuid': '3fc3cb53-c3fa-11e9-b9c5-12148b63a89a'}, {'sapCode': 'COSY', 'version': '2.4.1', 'buildGuid': '3fcf9f00-c3fa-11e9-b9c5-12148b63a89a'}, {'sapCode': 'CORG', 'version': '1.0', 'buildGuid': '3fc3cf0a-c3fa-11e9-b9c5-12148b63a89a'}, {'sapCode': 'CORE', 'version': '1.0', 'buildGuid': '3fc3d387-c3fa-11e9-b9c5-12148b63a89a'}, {'sapCode': 'CCXP', 'version': '2.2.1', 'buildGuid': '3fdc5e2b-c3fa-11e9-b9c5-12148b63a89a'}]

Creating Install ILST_26.0.1-ru_RU-macuniversal.app
.: replacing existing signature
Traceback (most recent call last):
  File "./ccdl.py", line 634, in <module>
    runccdl()
  File "./ccdl.py", line 522, in runccdl
    shutil.copyfile(icon_path, os.path.join(install_app_path,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Application Support/Adobe/Adobe Desktop Common/HDBox/Install.app/Contents/Resources/CreativeCloudInstaller.icns'
````

**Comment by Drovosek01** [comment]
Try reinstall CommandLine Tools

**Comment by int-0x03** [comment]
Oh, it's okey. I just install Adobe creative cloud and issue solved. Thanks.
