### ISSUE TITLE
Suddenly started getting a network error out of nowhere

### ISSUE THREAD

**Issue by nico671** [Drovosek01/adobe-packager#23]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/usr/local/lib/python3.9/site-packages/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 462, in read
    n = self.readinto(b)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 506, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python3.9/site-packages/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.9/site-packages/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(54, 'Connection reset by peer')", ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yes/Documents/adobe-packager/./ccdl.py", line 634, in <module>
    runccdl()
  File "/Users/yes/Documents/adobe-packager/./ccdl.py", line 589, in runccdl
    for data in response.iter_content(block_size):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 756, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(54, 'Connection reset by peer')", ConnectionResetError(54, 'Connection reset by peer'))
 44%|████████████████▊                     | 785M/1.77G [00:31<00:39, 24.7MiB/s]

Saving session...completed.

[Process completed]

**Comment by nico671** [comment]
it started out of nowhere as well, just trying to figure out if it's my network or its something that happened to the script

**Comment by thpryrchn** [comment]
Which package and version were you downloading? 

So I can try to reproduce. 

Did you try rebooting your computer, and router to see if something was up with your network?

Are you in a country that firewalls the internet? If so, maybe try a VPN through another country, like the USA. 

https://protonvpn.com/ has some free servers you can try.

**Comment by berritolam** [comment]
Last login: Tue Jan  4 08:05:43 on ttys000
user@user-MacBook-Pro ~ % /Users/user/Documents/Software/Adobe\ 2021\ Instalation/adobe-packager-master/ccdl.command ; exit;
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Users/user/Documents/Software/Adobe 2021 Instalation/adobe-packager-master/ccdl.command: line 9: [: =: unary operator expected
python3 found but non-functional
If you received a popup asking to install some tools, please accept.
Press [SPACE] when installation is complete, or any other key to abort.

why?

**Comment by thpryrchn** [comment]
> Last login: Tue Jan 4 08:05:43 on ttys000 user@user-MacBook-Pro ~ % /Users/user/Documents/Software/Adobe\ 2021\ Instalation/adobe-packager-master/ccdl.command ; exit; xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun /Users/user/Documents/Software/Adobe 2021 Instalation/adobe-packager-master/ccdl.command: line 9: [: =: unary operator expected python3 found but non-functional If you received a popup asking to install some tools, please accept. Press [SPACE] when installation is complete, or any other key to abort.
> 
> why?

Looks like your command line tools are not installed.. Sometimes a macOS update, or even a security update can break it... Try running this:
```xcode-select --install```
