### ISSUE TITLE
Stuck at process completed. No sign of further prompt.

### ISSUE THREAD

**Issue by kidfrom** [Drovosek01/adobe-packager#40]
My goal is to install Adobe Acrobat DC Pro.

The problem is that `ccdl.command` stops at `[process completed]`.

What I've did:
1. Download this repository. Unpack it at the download folders.
2. CTRL+left click the `ccdl.command` file.
3. Input `y` to prompt of `Do you want to make M1 native packages (Y/n)`

The log:
```
Last login: Mon Jun 20 15:02:35 on ttys000
/Users/x/Downloads/adobe-packager-master/ccdl.command ; exit;
x@xs-Mac-mini ~ % /Users/x/Downloads/adobe-packager-master/ccdl.command ; exit;
python3 found!
requests found!
starting ccdl
=================================
= Adobe macOS Package Generator =
============= 0.1.4 =============

Do you want to make M1 native packages (Y/n): y
Downloading products.xml

https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v4/products/all?_type=xml&channel=ccm,sti&platform=macuniversal,osx10-64,osx10&productType=Desktop
Source URL is: https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v4/products/all?_type=xml&channel=ccm,sti&platform=macuniversal,osx10-64,osx10&productType=Desktop
Source URL is: https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v4/products/all?_type=xml&channel=ccm,sti&platform=macarm64,macuniversal&productType=Desktop
Parsing products.xml
Traceback (most recent call last):
  File "./ccdl.py", line 662, in <module>
    runccdl()
  File "./ccdl.py", line 369, in runccdl
    products, cdn = parse_products_xml(products_xml)
  File "./ccdl.py", line 283, in parse_products_xml
    dependencies = list(
TypeError: 'NoneType' object is not iterable

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by sparm333** [comment]
Same happening here. I think maybe the adobe endpoint is no longer working (worked last week) since the scripts aren't able to iterate over the list of "products" the endpoint supposedly returns.

**Comment by lasithkoswattagamage** [comment]
Was enountering this issue a few hours ago too. I made a one line change to fix this issue 
```
# BEFORE
283:         dependencies = list(
284:            p.find('platforms/platform/languageSet/dependencies'))

# AFTER
283:         dependencies = p.findall('platforms/platform/languageSet/dependencies/dependency')
```

Its interesting to note that Adobe Packager was working completely fine a few hours ago. Perhaps an endpoint change was released that broke previous compatibility. 

Also interesting to note that the previous lines of code would generate a dependencies array of [None] if there were no dependencies declared in the products XML. The change I made simply produces an empty array [], if there are no dependencies declared in the products XML

**Comment by ZipperedJon** [comment]
Having the same issue here with an Intel mac, is it something wrong with the server side?

`=================================
= Adobe macOS Package Generator =
============= 0.1.4 =============

Do you want to make M1 native packages (y/N): n
Downloading products.xml

https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v4/products/all?_type=xml&channel=ccm,sti&platform=macuniversal,osx10-64,osx10&productType=Desktop
Source URL is: https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v4/products/all?_type=xml&channel=ccm,sti&platform=macuniversal,osx10-64,osx10&productType=Desktop
Parsing products.xml
Traceback (most recent call last):
  File "./ccdl.py", line 662, in <module>
    runccdl()
  File "./ccdl.py", line 369, in runccdl
    products, cdn = parse_products_xml(products_xml)
  File "./ccdl.py", line 283, in parse_products_xml
    dependencies = list(
TypeError: 'NoneType' object is not iterable
logout

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
`

**Comment by anavgupta1** [comment]
kidfrom what are the steps to make lasithkoswattagame's solution work?

**Comment by Taewan-P** [comment]
Where is ccdl.py?

**Comment by lasithkoswattagamage** [comment]
It is in the repository source code

**Comment by Taewan-P** [comment]
Sry my bad for the dumb question... Thank you for answering.

**Comment by lifeageometer** [comment]
How would I work it once I edit the code, when I try run the code too python it is unbearably slow.
