### ISSUE TITLE
ValueError: unknown locale: UTF-8

### ISSUE THREAD

**Issue by GabrielUlici** [Drovosek01/adobe-packager#44]
Please enter the desired version. Nothing for 23.4.1: 23.4

Traceback (most recent call last):
  File "./ccdl.py", line 662, in <module>
    runccdl()
  File "./ccdl.py", line 449, in runccdl
    deflocal = locale.getdefaultlocale()
  File "/Users/knucklehead/.pyenv/versions/3.6.8/lib/python3.6/locale.py", line 562, in getdefaultlocale
    return _parse_localename(localename)
  File "/Users/knucklehead/.pyenv/versions/3.6.8/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

On OS 12.4

<img width="481" alt="Screenshot 2022-06-28 at 14 34 56" src="https://user-images.githubusercontent.com/511812/176168917-199b1364-4614-410f-a472-2ddaf2a8babf.png">

**Comment by thpryrchn** [comment]
Hmmm.. What is the Country. default language on your mac?

**Comment by thpryrchn** [comment]
Fixed with latest commit
