### ISSUE TITLE
ConnectionRefusedError: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by Hyperblue** [Drovosek01/adobe-packager#73]
lease enter the URL version(v4/v5/v6) for downloading products.xml, or nothing for v6: 

Do you want to make M1 native packages (y/N): n

Downloading products.xml

Source URL is: https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v6/products/all?_type=xml&channel=ccm&channel=sti&platform=osx10-64,osx10,macarm64,macuniversal&productType=Desktop
Traceback (most recent call last):
  File "/Users/aaron/Library/Python/3.8/lib/python/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/aaron/Library/Python/3.8/lib/python/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Users/aaron/Library/Python/3.8/lib/python/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/Users/aaron/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/Users/aaron/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/Users/aaron/Library/Python/3.8/lib/python/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/Users/aaron/Library/Python/3.8/lib/python/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x10a7021f0>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Library/Python/3.8/lib/python/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/aaron/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/Users/aaron/Library/Python/3.8/lib/python/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='prod-rel-ffc-ccm.oobesaas.adobe.com', port=443): Max retries exceeded with url: /adobe-ffc-external/core/v6/products/all?_type=xml&channel=ccm&channel=sti&platform=osx10-64,osx10,macarm64,macuniversal&productType=Desktop (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10a7021f0>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/adobe-packager/ccdl.py", line 768, in <module>
    runccdl()
  File "/Users/aaron/adobe-packager/ccdl.py", line 483, in runccdl
    products_xml = get_products_xml(adobeurl)
  File "/Users/aaron/adobe-packager/ccdl.py", line 271, in get_products_xml
    return ET.fromstring(r(adobeurl))
  File "/Users/aaron/adobe-packager/ccdl.py", line 263, in r
    req = session.get(url, headers=headers)
  File "/Users/aaron/Library/Python/3.8/lib/python/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/Users/aaron/Library/Python/3.8/lib/python/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/aaron/Library/Python/3.8/lib/python/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/aaron/Library/Python/3.8/lib/python/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='prod-rel-ffc-ccm.oobesaas.adobe.com', port=443): Max retries exceeded with url: /adobe-ffc-external/core/v6/products/all?_type=xml&channel=ccm&channel=sti&platform=osx10-64,osx10,macarm64,macuniversal&productType=Desktop (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10a7021f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by Drovosek01** [comment]
Looks like problem with your installed Python or with your internet connection
