### ISSUE TITLE
EOF occurred in violation of protocol 

### ISSUE THREAD

**Issue by arminmacx** [Drovosek01/adobe-packager#77]
Hi,

i tried to download latest version of adobe products but each time i get error on last part of download and ccdl exit without downloading full package .

```
Downloading...

[ILST_28.1] Parsing available packages
[ILST_28.1] Selected 28 core packages and 4 non-core packages
Url is: https://ccmdls.adobe.com/AdobeProducts/ILST/28.1.0.141/macuniversal/607ed3b3-6755-47d8-ba73-960d83134cf8/AdobeIllustrator28-Core.zip
[ILST_28.1] Downloading AdobeIllustrator28-Core.zip
100%|███████████████████████████████████████████████████████████████████████████████████████| 1.01G/1.01G [07:40<00:00, 2.20MiB/s]
Url is: https://ccmdls.adobe.com/AdobeProducts/ILST/28.1.0.141/macuniversal/607ed3b3-6755-47d8-ba73-960d83134cf8/AdobeIllustrator28-Core_stripped.zip
[ILST_28.1] Downloading AdobeIllustrator28-Core_stripped.zip
100%|█████████████████████████████████████████████████████████████████████████████████████████| 824M/824M [05:16<00:00, 2.60MiB/s]
Url is: https://ccmdls.adobe.com/AdobeProducts/ILST/28.1.0.141/macuniversal/607ed3b3-6755-47d8-ba73-960d83134cf8/AdobeIllustrator28-Settings.zip
[ILST_28.1] Downloading AdobeIllustrator28-Settings.zip
Traceback (most recent call last):
  File "/Users/armin/Library/Python/3.9/lib/python/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/armin/Library/Python/3.9/lib/python/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/armin/Library/Python/3.9/lib/python/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/armin/Library/Python/3.9/lib/python/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/armin/Library/Python/3.9/lib/python/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/armin/Library/Python/3.9/lib/python/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/armin/Library/Python/3.9/lib/python/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/armin/Library/Python/3.9/lib/python/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/armin/Library/Python/3.9/lib/python/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ccmdls.adobe.com', port=443): Max retries exceeded with url: /AdobeProducts/ILST/28.1.0.141/macuniversal/607ed3b3-6755-47d8-ba73-960d83134cf8/AdobeIllustrator28-Settings.zip (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/armin/Downloads/adobe-packager-master/./ccdl.py", line 769, in <module>
    run_ccdl(products, cdn, sapCodes, allowedPlatforms)
  File "/Users/armin/Downloads/adobe-packager-master/./ccdl.py", line 714, in run_ccdl
    download_file(url, product_dir, s, v)
  File "/Users/armin/Downloads/adobe-packager-master/./ccdl.py", line 384, in download_file
    response = session.get(
  File "/Users/armin/Library/Python/3.9/lib/python/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/Users/armin/Library/Python/3.9/lib/python/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/armin/Library/Python/3.9/lib/python/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/armin/Library/Python/3.9/lib/python/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='ccmdls.adobe.com', port=443): Max retries exceeded with url: /AdobeProducts/ILST/28.1.0.141/macuniversal/607ed3b3-6755-47d8-ba73-960d83134cf8/AdobeIllustrator28-Settings.zip (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

Saving session...completed.
```

**Comment by arminmacx** [comment]
i already tried it with v6 xml and v5 xml

**Comment by arminmacx** [comment]
ok after lots of investigation, i see i need to download the latest version of Python from their site and point the executable file into my path, upgrade all outdated library and try again and now it fix the issue
